"""
Deploy dashboard as a static HTML file.

Pulls fresh data from all APIs, bakes it into the HTML so no server is needed,
and optionally uploads to SiteGround via SFTP.

Usage:
    python deploy.py                  # Bake data into HTML, save to dist/
    python deploy.py --upload         # Bake + upload to SiteGround via SFTP
    python deploy.py --days 90        # Bake with 90 days of data

Required .env keys for upload:
    SITEGROUND_HOST      — SFTP hostname
    SITEGROUND_USER      — SFTP username
    SITEGROUND_PASSWORD  — SFTP password (or use SSH key)
    SITEGROUND_PATH      — Remote path (e.g. /home/user/public_html/dashboard/)
"""

import os
import sys
import json
import re
import argparse
from datetime import datetime, timedelta
from dotenv import load_dotenv

load_dotenv()

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
DIST_DIR = os.path.join(PROJECT_DIR, "dist")
DASHBOARD_FILE = os.path.join(PROJECT_DIR, "marketing-dashboard.html")


def pull_fresh_data(days=30):
    """Pull fresh data from all APIs."""
    from tools.pull_all import pull_brand, transform_for_dashboard

    end_date = datetime.now().strftime("%Y-%m-%d")
    start_date = (datetime.now() - timedelta(days=days)).strftime("%Y-%m-%d")

    output = {
        "generated_at": datetime.now().isoformat(),
        "date_range": {"start": start_date, "end": end_date},
    }

    for b in ["rc", "rnr", "wl"]:
        print(f"  Pulling {b}...")
        raw = pull_brand(b, start_date, end_date)
        output[b] = transform_for_dashboard(raw)

    return output


def bake_into_html(data):
    """Replace the loadData() function to use baked-in data instead of fetching from API."""
    with open(DASHBOARD_FILE, "r") as f:
        html = f.read()

    data_json = json.dumps(data, indent=2)

    # Replace the loadData function to use baked data directly
    baked_loader = f"""// ══════════════════════════════════
// BAKED DATA — generated by deploy.py on {datetime.now().strftime("%b %d, %Y %I:%M %p")}
const BAKED_DATA = {data_json};

async function loadData(isRefresh) {{
  const json = BAKED_DATA;
  DATA = json;

  if (json.date_range) {{
    if (json.date_range.start) document.getElementById('date-from').value = json.date_range.start;
    if (json.date_range.end)   document.getElementById('date-to').value   = json.date_range.end;
  }}

  if (json.generated_at) {{
    document.getElementById('live-badge').style.display = 'inline-flex';
  }}

  if (!isRefresh) {{
    const hasRC  = json.rc  && !json.rc._error;
    const hasRNR = json.rnr && !json.rnr._error;
    const hasWL  = json.wl  && !json.wl._error;
    currentBrand = hasRC ? 'rc' : hasRNR ? 'rnr' : hasWL ? 'wl' : 'rc';

    document.documentElement.style.setProperty('--brand-color', getBrandColor(currentBrand));
    document.getElementById('page-title').textContent   = BRAND_NAMES[currentBrand];
    document.getElementById('eyebrow-brand').textContent = BRAND_NAMES[currentBrand];

    document.querySelectorAll('.nav-brand-item').forEach(o => {{
      o.classList.toggle('active', o.getAttribute('data-brand') === currentBrand);
    }});
  }}

  renderCurrentTab();
}}"""

    # Replace the original loadData function block
    pattern = r'// ══+\nasync function loadData\(isRefresh\) \{.*?\n\}'
    html = re.sub(pattern, baked_loader, html, flags=re.DOTALL)

    # Disable the date range picker refresh (no server to call)
    html = html.replace(
        "const resp = await fetch(`/api/refresh?start=${from}&end=${to}`, { method:'POST' });",
        "// Static mode — date range switching disabled"
    )
    html = html.replace(
        "const resp = await fetch(`/api/data?range=${range}`);",
        "// Static mode — range switching disabled"
    )

    return html


def upload_sftp(local_file):
    """Upload file to SiteGround via SFTP."""
    host = os.getenv("SITEGROUND_HOST", "")
    user = os.getenv("SITEGROUND_USER", "")
    password = os.getenv("SITEGROUND_PASSWORD", "")
    remote_path = os.getenv("SITEGROUND_PATH", "")

    if not all([host, user, remote_path]):
        print("Missing SFTP credentials. Add to .env:")
        print("  SITEGROUND_HOST=your-host.siteground.biz")
        print("  SITEGROUND_USER=your-username")
        print("  SITEGROUND_PASSWORD=your-password")
        print("  SITEGROUND_PATH=/home/user/public_html/dashboard/")
        return False

    try:
        import paramiko
    except ImportError:
        print("paramiko not installed. Run: pip install paramiko")
        return False

    remote_file = os.path.join(remote_path, "index.html")

    transport = paramiko.Transport((host, 18765))  # SiteGround uses port 18765
    transport.connect(username=user, password=password)
    sftp = paramiko.SFTPClient.from_transport(transport)

    # Ensure remote directory exists
    try:
        sftp.stat(remote_path)
    except FileNotFoundError:
        sftp.mkdir(remote_path)

    sftp.put(local_file, remote_file)
    sftp.close()
    transport.close()

    print(f"  Uploaded to {host}:{remote_file}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Deploy dashboard as static HTML")
    parser.add_argument("--days", type=int, default=30, help="Days of data to pull (default: 30)")
    parser.add_argument("--upload", action="store_true", help="Upload to SiteGround via SFTP")
    parser.add_argument("--skip-pull", action="store_true", help="Use existing .tmp/data.json instead of pulling fresh")
    args = parser.parse_args()

    print("=== Dashboard Deploy ===\n")

    # Step 1: Get data
    if args.skip_pull:
        data_file = os.path.join(PROJECT_DIR, ".tmp", "data.json")
        if not os.path.exists(data_file):
            print("No cached data found. Run without --skip-pull first.")
            return
        with open(data_file) as f:
            data = json.load(f)
        print("Using cached data from .tmp/data.json")
    else:
        print(f"Pulling fresh data ({args.days} days)...")
        data = pull_fresh_data(args.days)
        print("  Done.\n")

    # Step 2: Bake into HTML
    print("Baking data into HTML...")
    html = bake_into_html(data)

    os.makedirs(DIST_DIR, exist_ok=True)
    out_path = os.path.join(DIST_DIR, "index.html")
    with open(out_path, "w") as f:
        f.write(html)
    print(f"  Saved to {out_path}")
    size_kb = os.path.getsize(out_path) / 1024
    print(f"  Size: {size_kb:.0f} KB\n")

    # Step 3: Optional upload
    if args.upload:
        print("Uploading to SiteGround...")
        upload_sftp(out_path)

    print("\nDone! Open dist/index.html in a browser to preview.")


if __name__ == "__main__":
    main()
